# Generated by Django 4.2.1 on 2023-05-25 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vftapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testapi',
            name='alias',
        ),
        migrations.RemoveField(
            model_name='testapi',
            name='name',
        ),
    ]
